name: pm2_flutter_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.3
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  device_info_plus: ^9.0.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^1.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  google_maps_flutter: ^2.10.1
  location: ^8.0.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding_graph.png
    - assets/images/onboarding_man.png
    - assets/images/onboarding_people.png
    - assets/images/onboarding_thailand_map.png
    - assets/images/advice-aqi-wallpaper.png
    - assets/images/advice-people-wallpaper.jpg
    - assets/images/advice-pm-wallpaper.jpg
    - assets/images/building-wallpaper.png
    - assets/images/city-wallpaper.png
    - assets/icons/pm-1-icon.png
    - assets/icons/pm-2-icon.png
    - assets/icons/pm-2-icon.png
    - assets/icons/pm-3-icon.png
    - assets/icons/pm-5-icon.png
    - assets/icons/heart-icon.svg
    - assets/icons/cloud-haze-icon.svg

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont.ttf
    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/NotoSansThai-VariableFont.ttf
